xbaseURL: "https://tobiastober.com" 
title: Tobias Tober
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2

params:
    description: "I am a postdoctoral researcher in political science at the University of Konstanz. I am a member of the Department of Politics and Public Administration at the University of Konstanz, the Cluster of Excellence 'The Politics of Inequality', and a ZENiT Fellow at the Zukunftskolleg (Institute for Advanced Studies). My work investigates the implications of large-scale structural changes such as European integration, globalization, technological change, and climate change from a comparative perspective. I am particularly dedicated to understanding how these structural transformations affect the political economy of the welfare state both on the demand and the supply side. My research in this area has also covered areas like income inequality, business interests, and subjective well-being. In addition, I have a keen interest in applied quantitative methods and Bayesian statistics. My work has appeared in journals like Comparative Political Studies, the Journal of Politics, and the Socio-Economic Review."
    author: Tobias Tober
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tobias Tober
          subtitle: "I am a postdoctoral researcher in political science at the University of Konstanz. I am a member of the Department of Politics and Public Administration, the Cluster of Excellence *The Politics of Inequality*, and a ZENiT Fellow at the *Zukunftskolleg* (Institute for Advanced Studies). My work investigates the political implications of large-scale structural changes such as European integration, globalization, technological change, and climate change from a comparative perspective. I am particularly dedicated to understanding how these structural transformations affect the political economy of the welfare state, both in terms of demand and supply. My research in this area has also covered areas like income inequality, business interests, and subjective well-being. In addition, I have a keen interest in applied quantitative methods and Bayesian statistics. My work has appeared in journals like the *British Journal of Political Science*, *Comparative Political Studies*, and the *Journal of Politics*."
          imageUrl: "/pic.jpg"
          imageWidth: 150
          imageHeight: 180
          imageTitle: Tobias Tober
          buttons:
            - name: Publications
              url: publications/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: Email
          url: mailto:tobias.tober@uni-konstanz.de
        - name: Location
          url: location/
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.de/citations?user=LTQCyPoAAAAJ&hl=de
        - name: orcid
          url: https://orcid.org/0000-0001-7237-2936
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Tobias-Tober
        - name: Twitter
          url: https://twitter.com/TobiasFTober

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tobias Tober"
      icon: /pic.jpg
      iconHeight: 35

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
