baseURL: "www.tobiastober.com" 
title: Dr. Tobias Tober
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 

params:
    description: "I am a postdoctoral researcher in political science at the University of Konstanz and a member of the Konstanz Cluster of Excellence 'The Politics of Inequality'. My work investigates the implications of large-scale structural changes such as European integration, globalization, technological change, and climate change from a Comparative Political Economy perspective. I am particularly dedicated to understanding how these structural transformations affect the political economy of the welfare state, both in terms of popular preferences and public policies. Yet, my research in this area has also covered areas like income inequality, business interests, and subjective well-being. In addition, I have a keen interest in applied quantitative methods and Bayesian statistics. While these are my empirical weapons of choice, I have published qualitative research as well. My work has appeared in journals like Comparative Political Studies, the Journal of Politics, and the Socio-Economic Review."
    author: Tobias Tober
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Tobias Tober
          subtitle: "I am a postdoctoral researcher in political science at the University of Konstanz and a member of the Konstanz Cluster of Excellence 'The Politics of Inequality'. My work investigates the implications of large-scale structural changes such as European integration, globalization, technological change, and climate change from a Comparative Political Economy perspective. I am particularly dedicated to understanding how these structural transformations affect the political economy of the welfare state, both in terms of popular preferences and public policies. Yet, my research in this area has also covered areas like income inequality, business interests, and subjective well-being. In addition, I have a keen interest in applied quantitative methods and Bayesian statistics. While these are my empirical weapons of choice, I have published qualitative research as well. My work has appeared in journals like Comparative Political Studies, the Journal of Politics, and the Socio-Economic Review."
          imageUrl: "pic.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dr. Tobias Tober
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tobias.tober@uni-konstanz.de
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.de/citations?user=LTQCyPoAAAAJ&hl=de
        - name: GitHub
          url: 
        - name: Twitter
          url: https://twitter.com/TobiasFTober

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Prof. Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
